### ISSUE TITLE
Make generated images temporary

### ISSUE THREAD

**Issue by mbodmer** [peele/plantuml-preview#3]
Hi, thanks for this great plugin.

It would be nice if plantuml-preview would not generate the image files into the same directory where the source file is located.

The generated files should be temporary instead.
This would not "contaminate" the source directory with generated files.

Keep up the good work.

regards, Marc

**Comment by peele** [comment]
Thank you. I see a few options and some clarification would help:
- Provide a setting for an output directory for the generated files
  - This would end up being global and direct everything to this directory
  - If it's not set generate to current directory
- Delete the generated files on regenerate or preview close
  - Probably have to delete every time it's regenerated because the number of output files can change with multipage diagrams
  - Seems like a fair amount of overhead
- Don't generate files by running PlantUML with the pipe option
  - I'd have to look into this option, I know it exist but have not used it
  - If running with pipe option a separate command or functionality is needed to generate/save/copy the output when satisfied with the results

I appreciate your feedback. Specifying an output directory would be the simplest option.

_Edit 2015/08/15_
Another alternative is the OS temporary directory. Not sure how pipe handles multipage diagrams and I view that as a key feature.

**Comment by peele** [comment]
Output to OS temporary directory added to version 0.6.0. The global setting defaults to false. Setting to true will set the initial behavior for all previews. Setting can be controlled for each preview, does not affect the global setting.

**Comment by mbodmer** [comment]
Sorry to not give feedback sooner. What you did looks reasonable, thank you.
