### ISSUE TITLE
does not support component-- Note syntax

### ISSUE THREAD

**Issue by ssnyder** [peele/plantuml-preview#38]
Does not seem to support when a note is predefined and then used later on (when I comment out myobj -- N1 it displays the note on the upper right part of the diagram, not with the object where it belongs.  The Eclipse plugin works with this syntax - so I know it is valid.

```
@startuml
!pragma teoz true

package "Vendors" {
  frame Me as Me {
    component ATypeOfJavaService as atjs #paleTurquoise
  }

  frame vendorA {
    rectangle "A"
  }
}

package somePackage {
  component ATypeOfGateway as atg #darkTurquoise
  component conductor as c
}
node pr

interface "**START**" as st

note as N1
  #My notes are here
  #there are a few
  **showing some additional info
end note

st -> pr
pr -down-> c
atg <-down-> Nuance

''''''' this line creates the error message
atjs -- N1 
''''''''''''''''''''''''
@enduml

```

**Comment by peele** [comment]
The package does not contain a copy of the plantuml jar or modify in the input file. I only uses the current file and package settings to execute a command. You can see this command by opening the Atom dev tools window and looking at the console output.

For the above example uml I get the following diagram:
![image](https://user-images.githubusercontent.com/13669324/39662041-0f115738-502a-11e8-99e8-95ea6d89e522.png)

The example that I found of associating a note to diagram element used ".." instead of "--", but both work.

This is my jar version:
```
$ java -jar plantuml.2017.08.jar -checkversion
PlantUML version 2017.08 (Tue Mar 21 13:41:05 EDT 2017)

Last available version for download : 2018

Your version is up to date.
```
